### ISSUE TITLE
Temporary WASM HTTP failures in EnvoyExtensionPolicy do not get reconciled automatically

### ISSUE THREAD

**Issue by boomer41** [envoyproxy/gateway#5619]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: The expected value isn't returned, etc.

Consider the following (stripped) EnvoyExtensionPolicy:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: my-plugin
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: my-gateway
  wasm:
  - name: wasm-filter
    rootID: ""
    code:
      type: HTTP
      http:
        url: http://my-provider.my-namespace.svc.cluster.local/plugin.wasm
        sha256: 98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
    failOpen: true
    config:
      default_directives: default
      directives_map:
        default:
          - Include @recommended-conf
          - Include @crs-setup-conf
          - Include @owasp_crs/*.conf
```

When there is a temporary failure in downloading said plugin, the ExtensionPolicy will not get automatically reconciled. Because we use a simple pod to host our plugin, the pod may not be started when the extension policy gets created. The Gateway Controller then tries to download the plugin, but fails.

However, the controller does not retry reconciling said plugin. One has to explicitly trigger the reconciliation. And even annotating the CR does not work. One has to really change the underlying configuration to get the Gateway to do something.

The same happens with OCI images. When there is a temporary failure downloading the OCI image, it will not get retried.

This is contrary to the "Kubernetes Way" where reconciling will be tried again and again until it finally succeeds". 

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

- Add an Envoy extension policy containing a reference to an unknown service.
- Observe that the Extension Policy's status says that it failed to get configured.
- Apply a simple Pod and Service with an HTTP server hosting a plugin. You can use this Dockerfile to build an image with the Coraza WAF plugin.

```Dockerfile
FROM debian:12 AS builder

RUN apt update && \
    apt -y install unzip wget

# renovate: datasource=github-tags depName=corazawaf/coraza-proxy-wasm:
ARG CORAZA_WAF_VERSION="0.5.0"

RUN wget -O coraza-proxy-wasm.zip https://github.com/corazawaf/coraza-proxy-wasm/releases/download/${CORAZA_WAF_VERSION}/coraza-proxy-wasm-${CORAZA_WAF_VERSION}.zip && \
    unzip coraza-proxy-wasm.zip && \
    mv coraza-proxy-wasm.wasm plugin.wasm && \
    sha256sum plugin.wasm

FROM nginxinc/nginx-unprivileged:1.27.3 AS final

COPY --from=builder plugin.wasm /usr/share/nginx/html
```

- Observe that, even after hours, the Envoy Extension Policy will not reconcile and the HTTP server pod does not log any activity at all.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

Gateway 1.3.0 with the default envoy proxy version.
K8s 1.31.2

*Logs*:
>Include the access logs and the Envoy logs.

An example when the SHA checksum is (currently) invalid, but will be valid once the new pods spin up

````
   status:
    ancestors:
    - ancestorRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: my-gateway
        namespace: my-namespace
      conditions:
      - lastTransitionTime: "2025-03-27T11:54:29Z"
        message: 'Wasm: module downloaded from http://my-provider.my-namespace.svc.cluster.local/plugin.wasm
          has checksum ffff6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4,
          which does not match: 98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4.'
        observedGeneration: 8
        reason: Invalid
        status: "False"
        type: Accepted
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
```

**Comment by arkodg** [comment]
cc @zhaohuabing

**Comment by Avrmaster** [comment]
We are also affected by this. Helm install, Envoy Gateway v1.7.0.
And for us this is not just a transient startup inconvenience - automatic reconciliation is essential.

Envoy Proxy is managed by Envoy Gateway as the control plane. If a Wasm module fetch fails temporarily (for example due to startup concurrency, rollout bursts, or a short-lived internal HTTP/cache issue), the system should eventually converge to the desired state without requiring a manual spec change or restart.

From an operator perspective, the desired state is stable:
- the EnvoyExtensionPolicy exists
- the Wasm extension is valid
- Envoy Gateway should keep trying until proxies converge

Today, the behavior appears to be:
- transient fetch/load failure occurs
- the policy/proxy can remain stuck in a failed or partially applied state
- there is no automatic reconciliation path to eventual success

That breaks the control-plane contract. Temporary delivery failures should be retried/reconciled automatically.

In our case this matters especially during burst startup scenarios where many Envoy pods start at once - and control plane frequently just don't have a bandwidth to serve all OCI images at onces to every pod.
A subset may fail to load the Wasm from the EG-managed internal HTTP source, and they do not reliably recover afterward - and extension is not applied at all - it's not acceptable!

Expected behavior:
1. temporary Wasm fetch/load errors should trigger requeue/reconciliation
2. Envoy Gateway should continue reconciling until success
3. status should clearly distinguish temporary/retryable errors from permanent validation errors
4. proxies that missed the Wasm during startup should eventually converge without manual intervention

Thanks

**Comment by Avrmaster** [comment]
Hi!
@zhaohuabing @arkodg It would be highly appreciated, if at least basic exponential retry (1s, 2s, 4s etc.) for WASM image loading would be added into release 1.8.x that is expected in the April - unless a permanent fix is possible.
Do you think it is possible?
Thank you deeply.

**Comment by Roboman341** [comment]
Hi!
Also affected by this.

**Comment by Avrmaster** [comment]
@arkodg I don't think this should be labeled an enhancement — it's a critical bug.

A controller is supposed to retry transient failures until it succeeds. Here a temporary WASM/OCI fetch or checksum failure means the plugin just doesn't load, and all we're left with is errors in the console inside the Envoy proxy pod — no automatic recovery. You have to mutate the spec by hand to force a re-reconcile. Any startup or rollout blip silently leaves the filter permanently unconfigured.

Since a WASM plugin can carry critical functionality, this leaves the whole extension policy mechanism unreliable — we can't be sure the functionality ever loads. We have real production cases where it consistently fails to load on the first try under high load and then never retries. Ideally the controller would requeue with backoff on transient fetch/checksum errors instead of leaving the resource in a terminal state. Happy to help test any fix.

**Comment by zirain** [comment]
@jukie I recall you raised a PR about retry on this, what's the current status?

**Comment by zhaohuabing** [comment]
@boomer41 EG already retries on WASM HTTP fetch failures — the HTTP fetcher retries up to 5 times with exponential backoff, and retries on 5xx/network errors but not 4xx. It's intentionally bounded rather than infinite, because WasmCache.Get runs synchronously inside the Gateway API → IR translation, so retrying forever would block translation. Once the retries are exhausted, EG can't tell whether a persistently-failing registry is temporarily down or permanently broken, so it gives up and reports a TranslationError on the EnvoyExtensionPolicy status; the module just isn't programmed.

One mitigation would be to have the controller re-trigger reconciliation/translation once the Wasm registry becomes reachable again, since a registry recovering isn't a Kubernetes event and nothing currently re-drives the translation.

**Comment by catpk** [comment]
Thanks @zhaohuabing. I think there are two distinct fetch stages here — this issue (and the "HTTP fetcher retries 5×") covers the first, but our production failure is the second:
1. Control plane → plugin source (HTTP/OCI). The 5× backoff fetcher; needs a reconcile re-trigger once it gives up. This is the original ask.
2. Data plane (proxy) → EG's `wasm_cluster.` EG always programs the plugin into the proxy as a `remote` async data source pointing back at the control plane (:18002), for both HTTP and Image sources. This fetch has no `retry_policy` and a fixed 10s timeout — and it's where we lose WASM on rapid scale-ups. (Checked through v1.8.x — still not exposed; 1.8 only added TLS + dynamic modules for the code source.)
What every proxy gets:
```
code:
  remote:
    http_uri: { uri: https://envoy-gateway/…:18002/<sha>.wasm, cluster: wasm_cluster, timeout: 10s }
    sha256: <sha>
    # no retry_policy -> num_retries defaults to 1
```
Repro: single `envoy-gateway` replica, ~9 wasm filters merged (`mergeGateways`), scale a proxy fleet 2→15. New pods fetch at once → `wasm_cluster.upstream_rq_timeout` climbs (P90 fetch time hits the 10s cap) → `createWasm: failed to load (in progress/cached)` → `Plugin … failed to load.` With `failOpen: true` the pod still passes readiness (`/ready` on :19003 doesn't check WASM) and serves traffic with the filter silently absent, never recovering — there's no data-plane retry.
So even once the control-plane fetcher retries indefinitely, the data-plane `remote` fetch can still fail and stay failed.
Ask: could EG expose `retry_policy` + a configurable `timeout` on the data-plane WASM `RemoteDataSource` (via EnvoyExtensionPolicy.spec.wasm[].code or EnvoyProxy)? Today the only workarounds we've found are an index-based `EnvoyPatchPolicy` JSONPatch, or bypassing the fetch by staging the `.wasm` on disk (initContainer) and patching `code` to `local`. Happy to share a full config_dump / stats / scripted repro, or help with a PR. We just have a common project with @Avrmaster from previous comment

**Comment by jukie** [comment]
@zirain I previously opened https://github.com/envoyproxy/gateway/pull/8299 and will refresh it + link it here

**Comment by dmaclaury** [comment]
+1 for what @catpk outlined, this matches my experience using WASM filters with EG, in my use case, 3 unique WASM filters. 
During scale-ups, particularly rapid, we often have a few proxy pods that never pull the binary from EG successfully. 

As a stopgap, I had success using AWS LB Controllers' readiness gates in conjunction with a custom health check that checks a direct response route with the `failOpen: false` filters enabled. 

From my testing, readiness-based approaches (including init containers) do not work because the proxy pods do not receive full configuration until they are marked ready in the k8s API.

**Comment by zhaohuabing** [comment]
DP retries should be fixed in https://github.com/envoyproxy/gateway/pull/8299

**Comment by Avrmaster** [comment]
Hi, @zhaohuabing thank you for responding in the thread!
In what release version are you expecting #8299 to be included?

**Comment by jukie** [comment]
I'll need some time to refresh it and get it reviewed but in the meantime will track this issue in the 1.9 milestone. If anyone else would like to pick this up please feel free!

**Comment by boomer41** [comment]
Sorry, not yet completely fixed :)
The path Proxy->Gateway is now retried, but the Envoy extension policy custom resource still isn't retried :(
@zirain @jukie

**Comment by Avrmaster** [comment]
Hey @jukie, hope you're doing well!

Is this fix still on track for the v1.9.0 release on August 14th?

We're building some crucial functionality on WASM + Envoy Gateway and this issue is a blocker for us, so we're really looking forward to seeing it land. Happy to help with testing if that's useful.
