### ISSUE TITLE
Support the new FullDuplex bodystreaming mode implemented in Envoy

### ISSUE THREAD

**Issue by sanjaypujare** [envoyproxy/gateway#5620]
*Description*:
Envoy recently added a new processing mode FULL_DUPLEX_STREAMED as documented here https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/processing_mode.proto#enum-extensions-filters-http-ext-proc-v3-processingmode-bodysendmode with more details at https://github.com/envoyproxy/envoy/blob/ec32249b5630bff8b4cb1499b2707baea57d19b4/api/envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto#L99-L111

We would like to have this supported in Envoy Gateway as well. The doc https://gateway.envoyproxy.io/docs/api/extension_types/#extprocbodyprocessingmode doesn't include FULL_DUPLEX_STREAMED

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/processing_mode.proto#enum-extensions-filters-http-ext-proc-v3-processingmode-bodysendmode

https://gateway.envoyproxy.io/docs/api/extension_types/#extprocbodyprocessingmode

https://github.com/envoyproxy/envoy/blob/ec32249b5630bff8b4cb1499b2707baea57d19b4/api/envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto#L99-L111

**Comment by sanjaypujare** [comment]
CC @gsjurseth

**Comment by sanjaypujare** [comment]
Looks like this has already been done? https://github.com/envoyproxy/gateway/pull/5349 .

**Comment by arkodg** [comment]
this has been fixed with https://github.com/envoyproxy/gateway/pull/5349, should be available in the next v1.4 release

**Comment by pbhagwatGCP** [comment]
When is V1.4 release due? is there a planned date?

**Comment by sanjaypujare** [comment]
@arkodg it seems 1.4 RC1 is out but the full release is yet to be done. I looked at the release notes https://gateway.envoyproxy.io/news/releases/notes/v1.4.0-rc.1/ and I don't see any mention of full duplex mode there.   

And the docs still don't talk about full duplex in https://gateway.envoyproxy.io/docs/api/extension_types/#extprocbodyprocessingmode

Any idea when we will have 1.4 with full duplex support and docs? Thanks

**Comment by arkodg** [comment]
looks like there was a bug in v1.4.0, should be fixed in v1.4.1 https://github.com/envoyproxy/gateway/pull/6103

**Comment by sanjaypujare** [comment]
> looks like there was a bug in v1.4.0, should be fixed in v1.4.1 [#6103](https://github.com/envoyproxy/gateway/pull/6103)

Thanks for letting us know. When will 1.4.1 be out?
